export {default as Home} from "./Home"
export {default as Apple} from "./Apple"
export {default as Navbar} from "./Navbar"
export {default as Header} from "./Header"
export {default as Cards} from "./Cards"
export {default as Footer} from "./Footer"
export {default as Sos} from "./Sos"
export {default as Angry} from "./Angry"